# fly.toml app configuration file generated for sheerluck on 2023-12-25T17:12:50+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sheerluck"
primary_region = "arn"

[env]
  SHEERLUCK_FQDN = "sheerluck.fly.dev"
  SHEERLUCK_SQLITE_URL = "/data/sheerluck4.sqlite"

[build]
  dockerfile = "Dockerfile"

[mount]
  source="data"
  destination="/data"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

