# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

primary_region = "arn"

[env]
PETRAPP_SQLITE_URL = "/data/petrapp.sqlite3"
PETRAPP_TRACES_DIRECTORY = "/data/traces"
PETRAPP_LOGS_DIRECTORY = "/data/logs"
LITESTREAM_REPLICA_TYPE = "s3"

[build]
dockerfile = "Dockerfile"

[mount]
source = "data"
destination = "/data"
initial_size = "1GB"
auto_extend_size_threshold = 80
auto_extend_size_increment = "1GB"
auto_extend_size_limit = "5GB"

[http_service]
internal_port = 4000
force_https = true
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 0

[[vm]]
size = "shared-cpu-1x"
memory = "512mb"

[[metrics]]
port = 9090
path = "/metrics"
