package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"

	"github.com/myrjola/petrapp/internal/petra/domain"
	"github.com/myrjola/petrapp/internal/petra/notification"
	"github.com/myrjola/petrapp/internal/petra/service"
	"github.com/myrjola/petrapp/internal/platform/contexthelpers"
)

// makeDispatchFunc returns the dispatcher closure passed to notification.Scheduler.
// It loads the user's subscriptions, sends the payload to each, and prunes any
// 410'd subscriptions. The closure runs outside an HTTP context, so it
// re-establishes the authenticated-user-id via contexthelpers.
func makeDispatchFunc(
	logger *slog.Logger,
	svc *service.Service,
	sender *notification.Sender,
) notification.DispatchFunc {
	return func(ctx context.Context, push domain.ScheduledPush) error {
		ctx = context.WithValue(ctx, contexthelpers.AuthenticatedUserIDContextKey, push.UserID)
		ctx = context.WithValue(ctx, contexthelpers.IsAuthenticatedContextKey, true)

		// Recheck the user's opt-in — they may have flipped it off mid-rest.
		prefs, err := svc.GetUserPreferences(ctx)
		if err != nil {
			return fmt.Errorf("dispatch: get preferences: %w", err)
		}
		if !prefs.RestNotificationsEnabled {
			return nil
		}

		subs, err := svc.ListPushSubscriptions(ctx)
		if err != nil {
			return fmt.Errorf("dispatch: list subscriptions: %w", err)
		}
		if len(subs) == 0 {
			return nil
		}

		// Validate JSON shape — payload was generated by maybeSchedulePush.
		// Treat a corrupt payload as non-retryable: log and drop, since the row
		// is deleted after fire and resending wouldn't change the parse outcome.
		var probe map[string]any
		if jsonErr := json.Unmarshal([]byte(push.Payload), &probe); jsonErr != nil {
			logger.LogAttrs(ctx, slog.LevelWarn, "skip dispatch: bad payload",
				slog.Int("push_id", push.ID),
				slog.Any("error", jsonErr))
			return nil
		}

		for _, sub := range subs {
			sendToSubscription(ctx, logger, svc, sender, sub, []byte(push.Payload))
		}
		return nil
	}
}

// sendToSubscription pushes payload to a single subscription, pruning the row
// on 410/404 and logging non-fatal errors otherwise. Errors are intentionally
// not propagated — one bad subscription must not abort dispatch to the others.
func sendToSubscription(
	ctx context.Context,
	logger *slog.Logger,
	svc *service.Service,
	sender *notification.Sender,
	sub domain.PushSubscription,
	payload []byte,
) {
	sendErr := sender.Send(ctx, sub, payload)
	if sendErr == nil {
		return
	}
	if errors.Is(sendErr, notification.ErrSubscriptionGone) {
		if delErr := svc.DeletePushSubscriptionByID(ctx, sub.ID); delErr != nil {
			logger.LogAttrs(ctx, slog.LevelWarn, "prune gone subscription",
				slog.Int("sub_id", sub.ID),
				slog.Any("error", delErr))
		}
		return
	}
	logger.LogAttrs(ctx, slog.LevelWarn, "push send",
		slog.Int("sub_id", sub.ID),
		slog.Any("error", sendErr))
}
