app = 'petra-logshipper'
primary_region = 'arn'

[build]
  image = 'ghcr.io/superfly/fly-log-shipper:latest'

[[services]]
http_checks = []
internal_port = 8686

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
