name: Docker Build and Push
permissions:
  contents: read
  deployments: write
on:
  workflow_call:
    inputs:
      fly_app:
        description: |
          Mandatory Fly app name that is used in the image registry URI.
          
          For example, if the app name is `my-app`, the image URI will be `registry.fly.io/my-app:docker_tag`.
          Recommended to use the same name as in production and reuse the image URI across environments.
        required: true
        type: string
      docker_tag:
        required: true
        type: string
    outputs:
      docker_image_uri:
        description: "The URI of the Docker that was pushed by this workflow."
        value: registry.fly.io/${{ inputs.fly_app }}:${{ inputs.docker_tag }}

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: arn
  FLY_ORG: personal

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@63da3ecc5e2793b98a3f2519b3d75d4f4c11cec2
      - run: flyctl deploy --app ${{ inputs.fly_app }} --remote-only --build-only --push --image-label ${{ inputs.docker_tag }}
